version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: postgres17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devSchool
    ports: 
     - "5432:5432"
    volumes:
     - ./docker/setup.sql:/docker-entrypoint-initdb.d/init.sql
