

POST http://localhost:3333/courses
Content-Type:application/json

{
  "title": "Curso de Node.js",
  "description": "Cadastrei meu curso"
}

###

GET http://localhost:3333/courses

###
GET http://localhost:3333/courses/ed4ee337-b8d5-4730-8d41-d09d8a2a1012

###

DELETE  http://localhost:3333/courses/1



