

POST http://localhost:3333/courses
Content-Type:application/json

{
  "title": "Curso de React",
  "description": "Cadastrei meu curso"
}

###

GET http://localhost:3333/courses?page=1

###
GET http://localhost:3333/courses/dd80de97-01ba-48a2-adb9-ad05b2b1fc08

###

DELETE  http://localhost:3333/courses/cabddc02-5076-4bb7-ba75-7ab54ae1ad76

###

PUT http://localhost:3333/courses/bf16eaea-6932-41e8-82b8-a82a675e2360
Content-Type:application/json

{
  "title": "Curso de C++",
  "description": "Cadastrei meu curso C++"
} 

###

POST http://localhost:3333/sessions
Content-Type: application/json

{
  "email": "Daniel81@yahoo.com",
  "password": "123456"
}